title: "장대겸 | Portfolio & Blog"
description: "성균관대학교 통계학과 & 경제학 복수전공 | 데이터 사이언스 & 계리학"
baseurl: ""
url: "https://DaeGyeomJang.github.io"

theme: minima

author:
  name: "장대겸"
  email: "your_email@example.com"
  github: "DaeGyeomJang"
